parameters:
    gally.job.directory_path: !php/const Gally\Job\Service\JobManager::JOB_DIRECTORY_PATH

vich_uploader:
    db_driver: orm

    mappings:
        job:
            uri_prefix: /job/file
            upload_destination: '%kernel.project_dir%/%gally.job.directory_path%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
